{{- $nc := .Values.devicePlugin.nodeConfig | default dict }}
{{- if and .Values.devicePlugin.enabled (or $nc.yaml $nc.json) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vgpu-manager.device-plugin" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
data:
  {{- if $nc.yaml }}
  nodeConfig.yaml: |
    {{- $nc.yaml | nindent 4 }}
  {{- else if $nc.json }}
  nodeConfig.json: |
    {{- $nc.json | nindent 4 }}
  {{- end }}
{{- end }}