{{- $nc := .Values.devicePlugin.nodeConfig | default dict }}
{{- if .Values.devicePlugin.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vgpu-manager.device-plugin" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
      {{- include "vgpu-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
        vgpu-manager.io/ignore-webhook: "true"
        {{- include "vgpu-manager.selectorLabels" . | nindent 8 }}
        {{- with .Values.devicePlugin.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        device-plugin-config/checksum: {{ include (print $.Template.BasePath "/device-plugin/configmap.yaml") . | sha256sum }}
      {{- if .Values.devicePlugin.annotations }}
        {{- toYaml .Values.devicePlugin.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.devicePlugin.runtimeClassName }}
      runtimeClassName: {{ .Values.devicePlugin.runtimeClassName }}
      {{- end }}
      {{- include "vgpu-manager.imagePullSecrets" . | nindent 6 }}
      priorityClassName: system-node-critical
      {{- if .Values.devicePlugin.nodeSelector }}
      nodeSelector: {{ toYaml .Values.devicePlugin.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.devicePlugin.tolerations }}
      tolerations: {{ toYaml .Values.devicePlugin.tolerations | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vgpu-manager.device-plugin" . }}
      terminationGracePeriodSeconds: {{ .Values.devicePlugin.terminationGracePeriodSeconds }}
      hostPID: true
      hostNetwork: {{ .Values.devicePlugin.hostNetwork }}
      restartPolicy: Always
      initContainers:
        - name: install
          command: ["/bin/bash", "-c", "/scripts/install_files.sh"]
          image: {{ include "vgpu-manager.fullimage" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          resources:
            requests:
              cpu: 10m
              memory: 15Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: manager
              mountPath: /etc/vgpu-manager
              mountPropagation: Bidirectional
      containers:
        - name: device-plugin
          image: {{ include "vgpu-manager.fullimage" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:
            - device-plugin
            - --domain={{ default "nvidia.com" .Values.globalDomain | trimSuffix "/" }}
            - --kube-api-qps={{ .Values.devicePlugin.devicePlugin.commands.kubeApiQps }}
            - --kube-api-burst={{ .Values.devicePlugin.devicePlugin.commands.kubeApiBurst }}
            - --device-list-strategy={{ .Values.devicePlugin.devicePlugin.commands.deviceListStrategy | default "envvar" }}
            - --device-split-count={{ .Values.devicePlugin.devicePlugin.commands.deviceSplitCount | default 10 }}
            - --device-cores-scaling={{ .Values.devicePlugin.devicePlugin.commands.deviceCoresScaling | default 1.0 }}
            - --device-memory-scaling={{ .Values.devicePlugin.devicePlugin.commands.deviceMemoryScaling | default 1.0 }}
            - --device-memory-factor={{ .Values.devicePlugin.devicePlugin.commands.deviceMemoryFactor | default 1 }}
            - --pprof-bind-port={{ .Values.devicePlugin.devicePlugin.commands.pprofBindPort }}
            - --cgroup-driver={{ .Values.devicePlugin.cgroupDriver }}
            - --feature-gates={{ .Values.devicePlugin.devicePlugin.commands.featureGates }}
            - --mofed-enabled={{ .Values.devicePlugin.devicePlugin.commands.mofedEnabled }}
            - --gds-enabled={{ .Values.devicePlugin.devicePlugin.commands.gdsEnabled }}
            - --open-kernel-modules={{ .Values.devicePlugin.devicePlugin.commands.openKernelModules }}
            - --mig-strategy={{ .Values.devicePlugin.devicePlugin.commands.migStrategy | default "mixed" }}
            {{- if $nc.yaml }}
            - --node-config-path=/config/nodeConfig.yaml
            {{- else if $nc.json }}
            - --node-config-path=/config/nodeConfig.json
            {{- end }}
            - --v={{ .Values.devicePlugin.devicePlugin.commands.logLevel }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_MANAGER_DIR
              value: {{ .Values.devicePlugin.vgpuManagerDir | default "/etc/vgpu-manager" }}
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_MIG_MONITOR_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility,compute
          {{- if .Values.devicePlugin.devicePlugin.env }}
            {{- toYaml .Values.devicePlugin.devicePlugin.env | nindent 12 }}
          {{- end }}
          {{- if gt (int .Values.devicePlugin.devicePlugin.commands.pprofBindPort) 0 }}
          ports:
            - name: pprof1
              containerPort: {{ .Values.devicePlugin.devicePlugin.commands.pprofBindPort }}
          {{- end }}
          securityContext: {{ toYaml .Values.devicePlugin.securityContext | nindent 12 }}
          resources: {{ toYaml .Values.devicePlugin.devicePlugin.resources | nindent 12 }}
          volumeMounts:
            - name: kubelet
              mountPath: /var/lib/kubelet
            - name: manager
              mountPath: /etc/vgpu-manager
            - name: cgroup
              mountPath: /sys/fs/cgroup
            {{- if or $nc.yaml $nc.json }}
            - name: node-config
              mountPath: /config
            {{- end }}
        - name: device-monitor
          image: {{ include "vgpu-manager.fullimage" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:
            - device-monitor
            - --domain={{ default "nvidia.com" .Values.globalDomain | trimSuffix "/" }}
            - --kube-api-qps={{ .Values.devicePlugin.deviceMonitor.commands.kubeApiQps }}
            - --kube-api-burst={{ .Values.devicePlugin.deviceMonitor.commands.kubeApiBurst }}
            - --server-bind-port={{ .Values.devicePlugin.deviceMonitor.commands.serverBindPort | default 3456 }}
            - --pprof-bind-port={{ .Values.devicePlugin.deviceMonitor.commands.pprofBindPort }}
            - --cgroup-driver={{ .Values.devicePlugin.cgroupDriver }}
            - --feature-gates={{ .Values.devicePlugin.deviceMonitor.commands.featureGates }}
            {{- if $nc.yaml }}
            - --node-config-path=/config/nodeConfig.yaml
            {{- else if $nc.json }}
            - --node-config-path=/config/nodeConfig.json
            {{- end }}
            - --enable-rbac={{ .Values.devicePlugin.deviceMonitor.commands.enableRBAC | default false }}
            - --v={{ .Values.devicePlugin.deviceMonitor.commands.logLevel }}
          ports:
            - name: metrics
              containerPort: {{ .Values.devicePlugin.deviceMonitor.commands.serverBindPort | default 3456 }}
            {{- if gt (int .Values.devicePlugin.deviceMonitor.commands.pprofBindPort) 0 }}
            - name: pprof2
              containerPort: {{ .Values.devicePlugin.deviceMonitor.commands.pprofBindPort }}
            {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_MIG_MONITOR_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility,compute
          {{- if .Values.devicePlugin.deviceMonitor.env }}
            {{- toYaml .Values.devicePlugin.deviceMonitor.env | nindent 12 }}
          {{- end }}
          securityContext: {{ toYaml .Values.devicePlugin.securityContext | nindent 12 }}
          resources: {{ toYaml .Values.devicePlugin.deviceMonitor.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.devicePlugin.deviceMonitor.commands.serverBindPort | default 3456 }}
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.devicePlugin.deviceMonitor.commands.serverBindPort | default 3456 }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: kubelet
              mountPath: /var/lib/kubelet
            - name: manager
              mountPath: /etc/vgpu-manager
            - name: cgroup
              mountPath: /sys/fs/cgroup
            {{- if or $nc.yaml $nc.json }}
            - name: node-config
              mountPath: /config
            {{- end }}
      volumes:
        - name: kubelet
          hostPath:
            path: {{ .Values.devicePlugin.kubeletRootDir | default "/var/lib/kubelet" }}
        - name: manager
          hostPath:
            path: {{ .Values.devicePlugin.vgpuManagerDir | default "/etc/vgpu-manager" }}
            type: DirectoryOrCreate
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        {{- if or $nc.yaml $nc.json }}
        - name: node-config
          configMap:
            name: {{ include "vgpu-manager.device-plugin" . }}-config
        {{- end }}
{{- end }}