{{- if .Values.devicePlugin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vgpu-manager.device-plugin" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
    {{- include "vgpu-manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.devicePlugin.deviceMonitor.commands.serverBindPort | default 3456 }}
      targetPort: metrics
      protocol: TCP
    {{- if gt (int .Values.devicePlugin.devicePlugin.commands.pprofBindPort) 0 }}
    - name: pprof1
      port: {{ .Values.devicePlugin.devicePlugin.commands.pprofBindPort }}
      targetPort: pprof1
      protocol: TCP
    {{- end }}
    {{- if gt (int .Values.devicePlugin.deviceMonitor.commands.pprofBindPort) 0 }}
    - name: pprof2
      port: {{ .Values.devicePlugin.deviceMonitor.commands.pprofBindPort }}
      targetPort: pprof2
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/component: {{ include "vgpu-manager.device-plugin" . }}
    {{- include "vgpu-manager.selectorLabels" . | nindent 4 }}
{{- end }}