---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vgpu-manager-kubelet-plugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vgpu-manager-kubelet-plugin:role
rules:
  - apiGroups:
      - resource.k8s.io
    resources:
      - resourceclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - resource.k8s.io
    resources:
      - resourceclaimtemplates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - resource.k8s.io
    resources:
      - resourceslices
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - resource.k8s.io
    resources:
      - resourceclaims/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vgpu-manager-kubelet-plugin-as-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vgpu-manager-kubelet-plugin:role
subjects:
  - kind: ServiceAccount
    name: vgpu-manager-kubelet-plugin
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vgpu-manager-kubelet-plugin
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vgpu-manager-kubelet-plugin
  template:
    metadata:
      labels:
        app: vgpu-manager-kubelet-plugin
        vgpu-manager.io/ignore-webhook: "true"
    spec:
      initContainers:
        - name: init-container
          image: coldzerofear/vgpu-manager-dra:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: [bash, /usr/bin/kubelet-plugin-prestart.sh]
          env:
            - name: NVIDIA_DRIVER_ROOT
              value: /
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility,compute
            - name: KUBELET_REGISTRAR_DIRECTORY_PATH
              value: /var/lib/kubelet/plugins_registry
            - name: KUBELET_PLUGINS_DIRECTORY_PATH
              value: /var/lib/kubelet/plugins
          volumeMounts:
            - name: driver-root-parent
              mountPath: /driver-root-parent
              readOnly: true
        - name: init-install
          image: coldzerofear/vgpu-manager-dra:latest
          imagePullPolicy: IfNotPresent
          command: [bash, -c, /usr/bin/install_files.sh]
          resources:
            requests:
              cpu: 10m
              memory: 15Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: manager
              mountPath: /etc/vgpu-manager
              mountPropagation: Bidirectional
      containers:
        - name: kubelet-plugin
          image: coldzerofear/vgpu-manager-dra:latest
          imagePullPolicy: IfNotPresent
          command: [bash, -c]
          args:
            - |-
              # Conditionally mask the params file to prevent this container from
              # recreating any missing GPU device nodes. This is necessary, for
              # example, when running under nvkind to limit the set GPUs governed
              # by the plugin even though it has cgroup access to all of them.
              if [ "${MASK_NVIDIA_DRIVER_PARAMS}" = "true" ]; then
                cp /proc/driver/nvidia/params root/gpu-params
                sed -i 's/^ModifyDeviceFiles: 1$/ModifyDeviceFiles: 0/' root/gpu-params
                mount --bind root/gpu-params /proc/driver/nvidia/params
              fi
              hami-kubelet-plugin -v 6
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MASK_NVIDIA_DRIVER_PARAMS
              value: ""
            - name: NVIDIA_DRIVER_ROOT
              value: /
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: CDI_ROOT
              value: /var/run/cdi
            - name: HEALTHCHECK_PORT
              value: "4567"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility,compute
            - name: NVIDIA_MIG_CONFIG_DEVICES
              value: all
            - name: DRIVER_ROOT_CTR_PATH
              value: /driver-root
            - name: HOST_MANAGER_DIR
              value: /etc/vgpu-manager
            - name: KUBELET_REGISTRAR_DIRECTORY_PATH
              value: /var/lib/kubelet/plugins_registry
            - name: KUBELET_PLUGINS_DIRECTORY_PATH
              value: /var/lib/kubelet/plugins
          securityContext:
            privileged: true
          startupProbe:
            grpc:
              port: 4567
              service: liveness
            failureThreshold: 60
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            grpc:
              port: 4567
              service: liveness
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins_registry
              name: plugins-registry
            - mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
              name: plugins
            - mountPath: /var/run/cdi
              name: cdi
            - mountPath: /driver-root
              mountPropagation: HostToContainer
              name: driver-root
              readOnly: true
            - mountPath: /etc/vgpu-manager
              name: manager
      dnsPolicy: ClusterFirst
      priorityClassName: "system-cluster-critical"
      serviceAccount: vgpu-manager-kubelet-plugin
      serviceAccountName: vgpu-manager-kubelet-plugin
      securityContext: {}
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: ""
          name: plugins-registry
        - hostPath:
            path: /var/lib/kubelet/plugins
            type: ""
          name: plugins
        - hostPath:
            path: /var/run/cdi
            type: ""
          name: cdi
        - hostPath:
            path: /
            type: DirectoryOrCreate
          name: driver-root-parent
        - hostPath:
            path: /
            type: DirectoryOrCreate
          name: driver-root
        - hostPath:
            path: /etc/vgpu-manager
            type: DirectoryOrCreate
          name: manager